# FactionsTop configuration.

config-version: 1
settings:
  command-aliases:
  - "f top"
  ignored-faction-ids:
  - "none"
  - "safezone"
  - "warzone"
  - "0"
  - "-1"
  - "-2"
  factions-per-page: 8
  max-batch-size: 10
  max-queue-size: 200
  chunk-recalculate-millis: 120000
  batch-recalculate-millis: 15000
  enabled:
    CHESTS: false
    LIQUID: true
    PLACED: true
  detailed:
    CHESTS: true
    LIQUID: true
    PLACED: true
  perform-recalculate:
    UNLOAD: true
    CLAIM: true
    BREAK: true
    PLACE: true
    EXPLODE: true
    PISTON: true
  bypass-recalculate-delay:
    UNLOAD: true
    CLAIM: true
    BREAK: false
    PLACE: false
    EXPLODE: false
    PISTON: false
  spawner-prices:
    SLIME: 75000.00
    SKELETON: 30000.00
    ZOMBIE: 25000.00
  block-prices:
    EMERALD_BLOCK: 1250.00
    DIAMOND_BLOCK: 1000.00
    GOLD_BLOCK: 250.00
    IRON_BLOCK: 75.00
    REDSTONE_BLOCK: 25.00
    COAL_BLOCK: 25.00
