name: ${project.name}
main: net.novucs.ftop.FactionsTopPlugin
version: ${project.version}
description: ${project.description}
author: novucs
softdepend: [Essentials, Factions, Vault]

commands:
  ftop:
    aliases: [factionstop]
    description: Displays factions in order of worth.
    usage: /<command> [page]

permissions:
  factionstop.user:
    default: true
    children:
      factionstop.use: true

  factionstop.admin:
    default: op
    children:
      factionstop.reload: true
      factionstop.sign.break: true
      factionstop.sign.create: true
      factionstop.user: true

  factionstop.*:
    default: false
    children:
      factionstop.admin: true

  factionstop.use: {default: false}
  factionstop.reload: {default: false}
  factionstop.sign.break: {default: false}
  factionstop.sign.create: {default: false}